name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: ../dbt_packages
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: incremental
        +on_schema_change: sync_all_columns
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
dispatch:
- macro_namespace: dbt_utils
  search_order:
  - airbyte_utils
  - dbt_utils
vars:
  json_column: _airbyte_data
  models_to_source:
    airbyte_plan_subscriptions_ab1: public._airbyte_raw_airbyte_plan_subscriptions
    airbyte_plan_subscriptions_ab2: public._airbyte_raw_airbyte_plan_subscriptions
    airbyte_plan_subscriptions_ab3: public._airbyte_raw_airbyte_plan_subscriptions
    airbyte_plan_subscriptions: public._airbyte_raw_airbyte_plan_subscriptions
    airbyte_plans_ab1: public._airbyte_raw_airbyte_plans
    airbyte_plans_ab2: public._airbyte_raw_airbyte_plans
    airbyte_plans_ab3: public._airbyte_raw_airbyte_plans
    airbyte_plans: public._airbyte_raw_airbyte_plans
    airbyte_users_ab1: public._airbyte_raw_airbyte_users
    airbyte_users_ab2: public._airbyte_raw_airbyte_users
    airbyte_users_ab3: public._airbyte_raw_airbyte_users
    airbyte_users: public._airbyte_raw_airbyte_users
