version: 2
sources:
- name: public
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_airbyte_plan_subscriptions
  - name: _airbyte_raw_airbyte_plans
  - name: _airbyte_raw_airbyte_users
